NEO4J_HOSTNAME = 'localhost'
NEO4J_USER = 'neo4j'
NEO4J_PASSWORD = '1'
NEO4J_PORT = 32783

MONGODB_HOSTNAME = '192.168.1.81'
MONGODB_USER = ''
MONGODB_PASSWORD = ''
MONGODB_PORT = 27017
MONGODB_NAME = 'thesis-enrollment'
MONGODB_USERS_COLLECTION = 'users'

APP_HOST = 'localhost'
APP_PORT = 8080

SECRET_KEY = "Your_secret_string"