NEO4J_HOSTNAME = 'localhost'
NEO4J_PASSWORD = ''
NEO4J_PORT = 32768

MONGODB_HOSTNAME = 'localhost'
MONGODB_PASSWORD = ''
MONGODB_PORT = 27017
MONGODB_NAME = 'thesis-enrollment'
MONGODB_USERS_COLLECTION = 'users'

APP_HOST = 'localhost'
APP_PORT = 8080